export const Icon = {
  onboard1: require('./onboard1.png'),
  onboard2: require('./onboard2.png'),
  onboard3: require('./onboard3.png'),
  message: require('./message.png'),
  discover: require('./discover.png'),
  newfeed: require('./newfeed.png'),
  profile: require('./profile.png'),
  phonebook: require('./phonebook.png'),
  qrcode: require('./qrcode.png'),
  plus: require('./plus.png'),
  addfriend: require('./addfriend.png'),
  videocall: require('./videocall.png'),
  telephone: require('./telephone.png'),
};
