export const RouterName = {
  Register: 'Register',
  CreateCustomer: 'CreateCustomer',
  ConfirmOTP: 'ConfirmOTP',
  Login: 'Login',
  HomeMessage: 'HomeMessage',
  StartScreen: 'StartScreen',
  OnBoarding: 'OnBoarding',
  ForgetPassword: 'ForgetPassword',
  Phonebook: 'Phonebook',
  Discover: 'Discover',
  NewFeed: 'NewFeed',
  Profile: 'Profile',
  BottomTabBar: 'BottomTabBar',
  SearchScreen: 'SearchScreen',
  AuthenStack: 'AuthenStack',
  Message: 'Message',
  OptionMessage: 'OptionMessage',
  Setting: 'Setting',
  Personal: 'Personal',
  AddFriend: 'AddFriend',
  FriendRequest: 'FriendRequest',
  TabbarFriend: 'TabbarFriend',
  PersonalFriendRequest: 'PersonalFriendRequest',
  PostStatus: 'PostStatus',
  PreViewImage: 'PreViewImage',
};
